version: '2'
services:
  cups:
    image: a0js/rpi-cups:latest
    container_name: cups
    ports:
      - "631:631"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - config:/etc/cups
      - cache:/var/cache/cups
      - log:/var/log/cups
    privileged: true
volumes:
  config:
    driver: local
  cache:
    driver: local
  log:
    driver: local
